### ISSUE TITLE
no work in Android

### ISSUE THREAD

**Issue by cmauroie** [zenvisuals/ionic-angular-google-maps#1]
Hello,

The contribution is very good and work in the browser but when I go to try on a mobile android can not see the map.

**Comment by zenvisuals** [comment]
Hi @cmauroie,

Thanks for the feedback, the map shows up on my android device but the geolocation does not seems to be working, perhaps the version I was working with was too old. May I check with you what is your android and ionic version?

Cheers

**Comment by ghost** [comment]
Hello, it Works great on android web but not, turn on the GPS.
Ionic -v 1.7.8
Cordova -v 5.4.0

**Comment by zenvisuals** [comment]
Hi @SoyAndresHernandez,

Thanks for your feedback! I think I have to update the code to use the newer version of cordova and ionic. I will take a look at the code again and update accordingly. 

Let you guys know again

Cheers

**Comment by zenvisuals** [comment]
Hi Guys, by updating all the libraries and plugins, the issue seems to be resolved. Therefore i will be closing this ticket. 

Cheers
