### ISSUE TITLE
request

### ISSUE THREAD

**Issue by deryfebriantara** [zenvisuals/ionic-angular-google-maps#3]
how can i get an info popup from markers when it get clicked ? thank you in advance
-dery

**Comment by zenvisuals** [comment]
Hi @deryfebriantara,

According to Angular Google Maps API Documentation, you can use <ui-gmap-windows> directive to show the information popup. Inside the directive you can put any content you want, if you want to the content to be dynamic, it can be set inside the markers' model.

Please refer to http://angular-ui.github.io/angular-google-maps/?JRwnVeTsM4n98QWm-oHQDw&ved=0CBMQFjAAOAo&usg=AFQjCNGZWf3yx7Vg-YGZEM9xiHCJLP3Oeg#!/api/windows to see how it works.

I have also updated and commited the code for your reference. 

Cheers

**Comment by deryfebriantara** [comment]
Ok i will try. Thank you zen for your reply. I'm new in angular btw.

**Comment by zenvisuals** [comment]
No worries @deryfebriantara. Angular's concepts would need some time to digest so no worries about it :+1: I took a long time to understand them but I'm moving to another framework now.

Hope my answer helped you out.

Please refer to https://github.com/zenvisuals/ionic-angular-google-maps/commit/c27bd66c1274ba104ad5c2474e0e5624f7d6e655 to check out the code changes. 

Let me know if you have any more questions

Cheers!
