### ISSUE TITLE
On android device can not tap on marker

### ISSUE THREAD

**Issue by vaibhavmalushte** [zenvisuals/ionic-angular-google-maps#4]
Hi,

Thank you for such a wonderful example. 

I am not able to tap on markers on IOS / Android devices :( please advice.

Thank you,
Vaibhav

**Comment by deryfebriantara** [comment]
can i see the code @vaibhavmalushte  ? 
a week ago i'm using ionic-angular-google-maps and tap marker is working.
are you use data-tap-disabled="true" in map-canvas div?

**Comment by vaibhavmalushte** [comment]
Hi,
How are where to set data-tap-disabled="true" ?

here is my code
<code>
MechanicsModel.all()
        .then(function (result) {
            result.data.data.forEach(function(marker_data){
                console.log(marker_data);
                $scope.markers.push({
                    id: $scope.markers.length,
                    latitude: marker_data.lat,
                    longitude: marker_data.long,
                    icon: $scope.markericon,
                    content: "<div><b>"+marker_data.contact_person+"</b></br><b>"+marker_data.delar_name+"</b></br><b>"+marker_data.contact_number+"</b></br><b>"+marker_data.mobile_number+"</b></br><div>"                    

```
            });                         
        })      
    });
```

</code>

**Comment by deryfebriantara** [comment]
your code seems fine, to set data-tap-disabled="true"
here my example code in my tamplate : 

```
 <div id="map_canvas" data-tap-disabled="true">
            <ui-gmap-google-map center="map.center" zoom="map.zoom" draggable="true" options="options">
                <ui-gmap-markers models="markers" coords="'self'" icon="'icon'" click="onMarkerClick">
                    <ui-gmap-windows show="show">
                        <div ng-non-bindable>{{content}}</div>
                    </ui-gmap-windows>
                </ui-gmap-markers>
            </ui-gmap-google-map>
        </div>
```

you have to create function click on marker

```
 $scope.onMarkerClick = function(marker, eventName, model) {
          model.show = !model.show;
      }
```

i hope that will work on android device

**Comment by vaibhavmalushte** [comment]
Thanks for quick reply, I'll check and let you know. 
And thanks again for this example :+1:

**Comment by deryfebriantara** [comment]
ok you are welcome , let me know if it still doesn't work

**Comment by vaibhavmalushte** [comment]
It works :)

**Comment by zenvisuals** [comment]
Hi @deryfebriantara and @vaibhavmalushte,

I just saw this ticket being raised. Thanks @deryfebriantara for helping out to solve this issue. I really appreciate it.

@vaibhavmalushte, hope it's all well for you now :)

Please let me know if you have any more questions.

Cheers guys,
ZenVisuals

**Comment by vaibhavmalushte** [comment]
Hi,
One more help please. 
When I tried to set options for marker in $scope.markers.push() like animation or labelContent its not working 
<code>
options:{animation:'BOUNCE',labelContent: 'test'},
</code>

Thank you,
Vaibhav

**Comment by zenvisuals** [comment]
Hi @vaibhavmalushte,

In your <ui-gmap-markers> tag you need to include the options attribute and reference it to the a property in your markers model.

```
// HTML

<ui-gmap-markers models="markers" coords="'self'" icon="'icon'" options="'options'"></ui-gmap-markers>

// Note that the options attribute only reference a string so you need the single quote as well

// Javascript
$scope.markers.push({
              options: {
                animation: 1,
                labelContent: 'test'
              },
              id: $scope.markers.length,
              latitude: lat + (i * 0.002),
              longitude: long + (i * 0.002),
              icon: $scope.markericon,
              title: 'm' + i
          })
```

Take note you can't use 'BOUNCE' as value for the animation property, if you take a look at the Animation object in the Google Maps API, the constants BOUNCE, DROP, O or j refers to a number.

```
Animation: {
  BOUNCE: 1,
  DROP: 2,
  O: 3,
  j: 4
}
```

Hope this helps and let me know if you have any issues with this

Cheers and have a nice day :)

ZenVisuals

**Comment by vaibhavmalushte** [comment]
Thanks again.

Will take look at it and let you know if its (not) working :)

Appreciate your support +1

Thank you,
Vaibhav
